### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by moth1995** [gruco0002/triangle_strip#1]
hi im trying with a list of triangles of lenght 1168 and i have this error

```
C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils>py test.py
Traceback (most recent call last):
  File "test.py", line 1174, in <module>
    strip = find_strip(faces)
  File "C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils\triangle_strip.py", line 195, in find_strip
    result = find_strip_internal(
  File "C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils\triangle_strip.py", line 82, in find_strip_internal
    result = find_strip_internal(
  File "C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils\triangle_strip.py", line 164, in find_strip_internal
    result = find_strip_internal(
  File "C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils\triangle_strip.py", line 164, in find_strip_internal
    result = find_strip_internal(
  File "C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils\triangle_strip.py", line 164, in find_strip_internal
    result = find_strip_internal(
  [Previous line repeated 992 more times]
  File "C:\Users\marco\Documents\Visual Studio Code\PES_WE_JL_Model_Tool\file_structure\utils\triangle_strip.py", line 60, in find_strip_internal
    for i in range(len(triangles)):
RecursionError: maximum recursion depth exceeded in comparison
```

[test.zip](https://github.com/gruco0002/triangle_strip/files/8968904/test.zip)

i uploaded my testing file, i need to get the strip for those triangles, if you can improve the code in python or even another language but giving sort of like a library for python will be amazing i need something to convert triangle to triangle strip, i'm willing to pay for it

thanks a lot!

**Comment by gruco0002** [comment]
Hello, it seems that you tried to use the function for a rather big set of triangles. As stated in the module docstring:

```
    The performance and runtime of this solution is not optimal, but it is
    sufficient for small enough problems.
```

Since I am not actively developing the script, I can only suggest things, that might help you. As stated in my readme file I am open to any improvements for the code.

If you read the code, you will find out, that the algorithm tries out each combination of vertices recursively in order to find a possible solution. Thereby it is guided by a heuristic, that tries to minimize the 'usage' of each vertex.

For the whole process the script uses recursion. Your input seems to be big enough, that python reaches its maximum recursion depth, before finding a solution. Therefore you could:

- Increase the maximum recursion depth (https://docs.python.org/3/library/sys.html#sys.setrecursionlimit)
- Split your problem up into smaller problems and solve them independently
- Try to rewrite the solution to an iterative one

Note that no matter what, the runtime will be in general quite bad for solving the problem this way. Since it was sufficient for me (as I only had a small input) I did not take the time to investigate alternative solutions. Perhaps there are better ones out there.

I hope this helps you getting closer to a solution.
